server:
  port: 8080

spring:
  config:
    import:
    - classpath:/application-database.yml # for AWS RES(MySQL)
#    - classpath:/application-oauth.yml    # for Google OAuth

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none  # only validate or none
    properties:
      hibernate:
#        show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace