// ifndef::snippets[]
// = :snippets: ../../build/generated-snippets
// endif::[]
= 멘질멘질 REST API 문서
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:
:sectnums:

== 회원가입

=== 이메일 중복 확인
==== 성공
===== 회원가입이 가능한 경우
요청한 이메일이 가입되어있지 않은 경우

operation::api/auth/signup-is-available/true[snippets='http-request,request-parameters']
operation::api/auth/signup-is-available/true[snippets='http-response,response-fields']

==== 실패
===== 회원가입이 불가능한 경우
요청한 이메일이 이미 가입되어있는 경우

operation::api/auth/signup-is-available/false[snippets='http-request']
operation::api/auth/signup-is-available/false[snippets='http-response']

=== 닉네임 중복 확인

==== 성공
===== 사용할 수 있는 닉네임 형식인 경우
operation::api/auth/check-nickname/true[snippets='http-request,request-parameters']
operation::api/auth/check-nickname/true[snippets='http-response,response-fields']

==== 실패
===== 닉네임에 공백이 포함된 경우
operation::api/auth/check-nickname/false-blank[snippets='http-request']
operation::api/auth/check-nickname/false-blank[snippets='http-response']

===== 닉네임에 특수문자가 포함된 경우
operation::api/auth/check-nickname/false-special-character[snippets='http-request']
operation::api/auth/check-nickname/false-special-character[snippets='http-response']

===== 닉네임이 이미 사용 중인 경우(존재하는 경우)
operation::api/auth/check-nickname/false-conflict[snippets='http-request']
operation::api/auth/check-nickname/false-conflict[snippets='http-response']


=== 회원 가입

==== 성공
operation::api/auth/signup/true[snippets='http-request,request-fields']
operation::api/auth/signup/true[snippets='http-response,response-fields']

==== 실패
===== 닉네임에 공백이 포함되어 있는 경우
operation::api/auth/signup/false-blank[snippets='http-request']
operation::api/auth/signup/false-blank[snippets='http-response']

===== 닉네임에 특수문자가 포함되어 있는 경우
operation::api/auth/signup/false-special-character[snippets='http-request']
operation::api/auth/signup/false-special-character[snippets='http-response']

===== 닉네임에 null 값이 들어온 경우
operation::api/auth/signup/false-null[snippets='http-request']
operation::api/auth/signup/false-null[snippets='http-response']

===== 학점이 4 초과한 값이 들어온 경우
operation::api/auth/signup/false-score-max[snippets='http-request']
operation::api/auth/signup/false-score-max[snippets='http-response']




== 로그인
=== 로그인
==== 성공
operation::api/auth/signin/success[snippets='http-request,request-fields']
operation::api/auth/signin/success[snippets='http-response,response-fields']

==== 실패
===== 플랫폼이 google, kakao 가 아닌 경우
operation::api/auth/signin/fail-provider[snippets='http-request']
operation::api/auth/signin/fail-provider[snippets='http-response']



== 팔로우
=== 팔로우 요청
==== 팔로우가 되어있지 않은 경우
팔로우가 생성된다.

operation::api/follow/create/201/true[snippets='http-request,request-fields']
operation::api/follow/create/201/true[snippets='http-response,response-fields']

==== 이미 팔로우가 되어 있는 경우
팔로우가 해제된다.

operation::api/follow/create/201/false[snippets='http-request,request-fields']
operation::api/follow/create/201/false[snippets='http-response,response-fields']

==== 서버 오류

operation::api/follow/create/500[snippets='http-request,request-fields']
operation::api/follow/create/500[snippets='http-response,response-fields']

=== 팔로우 상태 확인

==== 팔로우가 되어있는 경우
return true

operation::api/follow/check-status/true[snippets='http-request,request-parameters']
operation::api/follow/check-status/true[snippets='http-response,response-fields']

==== 팔로우가 되어있지 않은 경우
return false

operation::api/follow/check-status/false[snippets='http-request,request-parameters']
operation::api/follow/check-status/false[snippets='http-response,response-fields']
