// ifndef::snippets[]
// = :snippets: ../../build/generated-snippets
// endif::[]
= 멘질멘질 REST API 문서
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:
:sectnums:

== 회원가입

=== 이메일 검증
==== 회원가입이 가능한 경우
요청한 이메일이 가입되어있지 않은 경우

operation::api/auth/signup-is-available/true[snippets='http-request,request-parameters']
operation::api/auth/signup-is-available/true[snippets='http-response,response-fields']

==== 회원가입이 불가능한 경우
요청한 이메일이 이미 가입되어있는 경우

operation::api/auth/signup-is-available/false[snippets='http-request,request-parameters']
operation::api/auth/signup-is-available/false[snippets='http-response,response-fields']


== 팔로우
=== 팔로우 요청
==== 팔로우가 되어있지 않은 경우
정상적으로 팔로우 요청이 처리된다.

operation::api/follow/request/201/true[snippets='http-request,request-fields']
operation::api/follow/request/201/true[snippets='http-response,response-fields']

==== 이미 팔로우가 되어 있는 경우
팔로우 상태게 해제된다.

operation::api/follow/request/201/false[snippets='http-request,request-fields']
operation::api/follow/request/201/false[snippets='http-response,response-fields']

==== 서버 오류

operation::api/follow/request/500[snippets='http-request,request-fields']
operation::api/follow/request/500[snippets='http-response,response-fields']
