name: Java CI with Gradle in main branch

on:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # workflow 실행 전 기본적으로 checkout 필요
    # 최신 버전은 v3
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin' # jdk를 제공하는 vender사 이름 ex. zulu, adopt, microsoft
        
    ## Create properties
    - name: make application-database.yml
      run: 
        touch ./src/main/resources/application-database.yml |
        echo "${{env.APPLICATION_DATABASE}}" | base64 --decode > ./src/main/resources/application-database.yml
#     - uses: actions/upload-artifact@v3
#       with: 
#         name: application-database.yml 
#         path: ./src/main/resources/application-database.yml

    - name: make application-oauth.yml
      run: 
        touch ./src/main/resources/application-oauth.yml |
        echo "${{env.APPLICATION_OAUTH}}" | base64 --decode > ./src/main/resources/application-oauth.yml
#     - uses: actions/upload-artifact@v3
#       with: 
#         name: application-oauth.yml 
#         path: ./src/main/resources/application-oauth.yml

    - name: make test/resources/application-database-test.yml
      run: 
        touch src/test/resources/application-database-test.yml |
        echo "${{env.APPLICATION_TEST}}" | base64 --decode > src/test/resources/application-database-test.yml

    - name: upload application-database-test.yml
      uses: actions/upload-artifact@v3
      with: 
        name: application-database-test.yml 
        path: src/test/resources/application-database-test.yml

    ## Gradle
    - name: Cache gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
        
    - name: Build with Gradle
      run : ./gradlew clean build

    ## Docker
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64
        push: true
        # tags: ${{ secrets.DOCKERHUB_REPO }}:${{ github.sha }}  
        tags: ${{ secrets.DOCKERHUB_REPO }}:latest

