name: Gradle CI/CD with Docker, EC2

on:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # workflow 실행 전 기본적으로 checkout 필요
    # 최신 버전은 v3
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin' # jdk를 제공하는 vender사 이름 ex. zulu, adopt, microsoft
        
    ## Create properties
    - name: make application-database.yml
      shell: bash
      run: |
        touch src/main/resources/application-database.yml 
        echo "${{secrets.APPLICATION_DATABASE_PROD}}" > src/main/resources/application-database.yml

    - name: make application-security.yml
      shell: bash
      run: |
        touch src/main/resources/application-security.yml 
        echo "${{secrets.APPLICATION_OAUTH_PROD}}" > src/main/resources/application-security.yml

    - name: make test/resources/application-database-test.yml
      shell: bash
      run: |
        touch src/test/resources/application-database-test.yml 
        echo "${{secrets.APPLICATION_TEST_PROD}}" > src/test/resources/application-database-test.yml


    ## Gradle
    - name: Cache gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
        
    - name: Build with Gradle
      run : ./gradlew clean build

    ## Docker
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64
        push: true
        # tags: ${{ secrets.DOCKERHUB_REPO_PROD }}:${{ github.sha }}  
        tags: ${{ secrets.DOCKERHUB_REPO_PROD }}:latest

  deploy:
    needs: build  # build 이후에 실행되도록 설정
    runs-on: ubuntu-latest
    steps:
      - name: connect EC2 instance and deploy docker images 
        uses: appleboy/ssh-action@v0.1.10
        with: 
          host: ${{ secrets.AWS_EC2_HOST_IP_PROD }}
          username: ${{ secrets.AWS_EC2_USERNAME_PRDO }}
          key: ${{ secrets.AWS_SSH_KEY }}
          # port: ${{ secrets.AWS_SSH_PORT }} # 생략하면 default 22

          # kill container -> remove container -> remove image -> pull new image -> run
          script: |
            sudo docker kill ${{ secrets.PROJECT_NAME }}  
            sudo docker rm ${{ secrets.PROJECT_NAME }} 
            sudo docker rmi ${{ secrets.DOCKERHUB_REPO_PROD }}

            sudo docker pull ${{ secrets.DOCKERHUB_REPO_PROD }}:latest
            sudo docker run -d --name ${{ secrets.PROJECT_NAME }} -p 80:${{ secrets.APPLICATION_PORT }} ${{ secrets.DOCKERHUB_REPO_PROD }}:latest
